CREATE TABLE grupo(
	codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO grupo (nome) values('DESENVOLVIMENTO');
INSERT INTO grupo (nome) values('GERENCIAMENTO');
INSERT INTO grupo (nome) values('QUALIDADE');
